<?php
global $messages;
$messages['select_event'] = _t('TO_VIEW_AN_EVENT_YOU_HAVE_TO_FIRST_SELECT_AN_EVENT_FROM_THE_EVENT_LIST_');
$messages['event_not_found'] = _t('EVENT_DOES_NOT_EXIST_'); 
$messages['act_not_found'] = _t('REQUESTED_ACT_RECORD_DOES_NOT_EXIST_'); 
$messages['involvement_not_found'] = _t('REQUESTED_INVOLVEMENT_DOES_NOT_EXIST');
$messages['information_not_found'] = _t('REQUESTED_INFORMATION_DOES_NOT_EXIST');
$messages['intervention_not_found'] = _t('REQUESTED_INTERVENTION_DOES_NOT_EXIST');
$messages['coe_not_found'] = _t('CHAIN_OF_EVENTS_DOES_NOT_EXIST');
