DROP TABLE IF EXISTS `data_dict_l10n`;
DROP TABLE IF EXISTS `data_dict`;
DROP TABLE IF EXISTS `data_dict_original`;

CREATE TABLE IF NOT EXISTS `data_dict` (
    `field_number` varchar(60) NOT NULL default '',
    `field_label` varchar(100) default NULL,
    `field_type` varchar(60) default NULL,
    `datatype` varchar(60) default NULL,
    `label_number` varchar(60) default NULL,
    `list_code` varchar(60) default NULL,
    `is_repeat` varchar(60) default NULL,
    `clar_note` varchar(60) default NULL,
    `field_name` varchar(100) default NULL,
    `link_table` varchar(60) default NULL,
    `link_field` varchar(60) default NULL,  
    `remove` varchar(60) default NULL,
    `chk_remove` varchar(60) default NULL,
    `num_levels` varchar(60) default NULL,
    `lite` varchar(60) default NULL,
    `bool_def` varchar(60) default NULL,
    `numb_def` varchar(60) default NULL,
    `entity` varchar(60) default NULL,
    `find` varchar(60) default NULL,
    `essential` varchar(1) default 'n',
    `enabled` varchar(1) NOT NULL default 'y',
    `visible_new` varchar(1) NOT NULL default 'y',
    `visible_edit` varchar(1) NOT NULL default 'y',
    `visible_view` varchar(1) NOT NULL default 'y',
    `visible_search` varchar(1) NOT NULL default 'y',
    `visible_search_display` varchar(1) NOT NULL default 'y',
    `visible_browse` varchar(1) NOT NULL default 'n',
    `visible_browse_editable` varchar(1) NOT NULL default 'y',
    `validation` varchar(100) default NULL,
    `required` varchar(1) default 'n',
    `visible_adv_search` varchar(1) NOT NULL default 'y',
    `visible_adv_search_display` varchar(1) NOT NULL default 'y',
    PRIMARY KEY  (`field_number`)
) ENGINE=InnoDB ;

CREATE TABLE IF NOT EXISTS `data_dict_original` (
    `field_number` varchar(60) NOT NULL default '',
    `field_label` varchar(100) default NULL,
    `field_type` varchar(60) default NULL,
    `datatype` varchar(60) default NULL,
    `label_number` varchar(60) default NULL,
    `list_code` varchar(60) default NULL,
    `is_repeat` varchar(60) default NULL,
    `clar_note` varchar(60) default NULL,
    `field_name` varchar(100) default NULL,
    `link_table` varchar(60) default NULL,
    `link_field` varchar(60) default NULL,  
    `remove` varchar(60) default NULL,
    `chk_remove` varchar(60) default NULL,
    `num_levels` varchar(60) default NULL,
    `lite` varchar(60) default NULL,
    `bool_def` varchar(60) default NULL,
    `numb_def` varchar(60) default NULL,
    `entity` varchar(60) default NULL,
    `find` varchar(60) default NULL,
    `essential` varchar(1) default 'n',
    `enabled` varchar(1) NOT NULL default 'y',
    `visible_new` varchar(1) NOT NULL default 'y',
    `visible_edit` varchar(1) NOT NULL default 'y',
    `visible_view` varchar(1) NOT NULL default 'y',
    `visible_search` varchar(1) NOT NULL default 'y',
    `visible_search_display` varchar(1) NOT NULL default 'y',
    `visible_browse` varchar(1) NOT NULL default 'n',
    `visible_browse_editable` varchar(1) NOT NULL default 'y',
    `validation` varchar(100) default NULL,
    `required` varchar(1) default 'n',
    `visible_adv_search` varchar(1) NOT NULL default 'y',
    `visible_adv_search_display` varchar(1) NOT NULL default 'y',
    PRIMARY KEY  (`field_number`)
) ENGINE=InnoDB ;


CREATE TABLE IF NOT EXISTS `data_dict_l10n` (
   `msgid` VARCHAR( 60 ) NOT NULL ,
   `locale` VARCHAR( 20 ) NOT NULL ,
   `msgstr` TEXT CHARACTER SET utf8 NOT NULL,
   PRIMARY KEY (`msgid`,`locale`),
   FOREIGN KEY (`msgid`)  REFERENCES data_dict(field_number)
) ENGINE = InnoDB ;

--
-- Dumping data for table `data_dict`
--

INSERT INTO `data_dict` (`field_number`, `field_label`, `field_type`, `datatype`, `label_number`, `list_code`, `is_repeat`, `clar_note`, `field_name`, `link_table`, `link_field`, `remove`, `chk_remove`, `num_levels`, `lite`, `bool_def`, `numb_def`, `entity`, `find`, `essential`, `enabled`, `visible_new`, `visible_edit`, `visible_view`, `visible_search`, `visible_search_display`, `visible_browse`, `visible_browse_editable`, `validation`, `required`, `visible_adv_search`, `visible_adv_search_display`) VALUES
('0101', 'Event Record Number', 'hidden', 'I', '0101', '0', 'N', 'n', 'event_record_number', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'Y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', '', 'n', 'y', 'y'),
('0102', 'Event Title', 'text', 'C', '0102', '0', 'N', 'n', 'event_title', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'y', 'y', 'y', 'y', '', 'y', 'y', 'y'),
('0108', 'Confidentiality', 'radio', 'Y', '0108', '0', 'N', 'n', 'confidentiality', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0111', 'Geographical Term', 'mt_tree', 'L', '0111', '15', 'Y', 'y', 'geographical_term', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0112', 'Local Geographical Area', 'mt_tree', 'L', '0112', '63', 'Y', 'y', 'local_geographical_area', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0113', 'Initial Date', 'date', 'D', '0113', '0', 'N', 'y', 'initial_date', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'y'),
('0114', 'Final Date', 'date', 'D', '0114', '0', 'N', 'y', 'final_date', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'y'),
('0115', 'Event Description', 'textarea', 'M', '0115', '0', 'N', 'n', 'event_description', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0116', 'Impact of Event', 'text', 'M', '0116', '0', 'N', 'n', 'impact_of_event', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'y', 'n', 'y', 'y', '', 'n', 'y', 'n'),
('0150', 'Remarks', 'textarea', 'M', '0150', '0', 'N', 'n', 'remarks', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0151', 'Violation Status', 'mt_tree', 'L', '0151', '41', 'N', 'y', 'violation_status', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0152', 'Violation Index', 'mt_tree', 'L', '0152', '02', 'Y', 'n', 'violation_index', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0153', 'Rights Affected', 'mt_tree', 'L', '0153', '03', 'Y', 'n', 'rights_affected', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0154', 'HURIDOCS Index terms', 'mt_select', 'L', '0154', '01', 'Y', 'n', 'huridocs_index_terms', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0155', 'Local Index', 'mt_select', 'L', '0155', '61', 'Y', 'n', 'local_index', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0156', 'Other Thesaurus', 'mt_tree', 'L', '0156', '68', 'Y', 'n', 'other_thesaurus', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0160', 'Date Received', 'date', 'D', '0160', '0', 'N', 'y', 'date_received', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0161', 'Date of Entry', 'date', 'D', '0161', '0', 'N', 'n', 'date_of_entry', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0162', 'Entered by', 'text', 'C', '0162', '0', 'N', 'n', 'entered_by', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0163', 'Project Title', 'text', 'M', '0163', '0', 'N', 'n', 'project_title', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'y'),
('0165', 'Comments', 'textarea', 'M', '0165', '0', 'N', 'n', 'comments', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0166', 'Supporting Documents', 'document', 'M', '0166', '0', 'N', 'n', 'supporting_documents', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'n', 'n'),
('0167', 'Files', 'textarea', 'C', '0167', '0', 'N', 'n', 'files', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0168', 'Record Grouping', 'text', 'C', '0168', '0', 'N', 'n', 'record_grouping', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0170', 'Date Updated', 'date', 'D', '0170', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0171', 'Updated By', 'text', 'M', '0171', '0', 'N', 'n', 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'event', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0172', 'Monitoring Status', 'mt_select', 'L', '0172', '43', 'N', 'y', 'monitoring_status', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'event', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0901', 'Person Record Number', 'hidden', 'I', '0901', '0', 'N', 'n', 'person_record_number', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'y', '', 'y', 'y', 'y', 'y', 'y', 'y', 'n', '', 'n', 'y', 'y'),
('0902', 'Counting unit', 'mt_select', 'L', '0902', '07', 'N', 'n', 'counting_unit', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', 'y', 'y', '', 'n', 'y', 'n'),
('0903', 'Name', 'text', 'C', '0903', '0', 'N', 'n', 'person_name', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'y'),
('0904', 'Other names', 'text', 'M', '0904', '0', 'N', 'n', 'other_names', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'y', 'y', '', 'y', '', 'n', 'y', 'y'),
('0908', 'Confidentiality', 'radio', 'Y', '0908', '0', 'N', 'n', 'confidentiality', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0910', 'Address', 'address', 'T', '0910', '0', 'N', 'n', 'person_addresses', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'y', 'n', 'n', '', 'n', 'n', 'y'),
('0911', 'Date of Birth', 'date', 'D', '0911', '0', 'N', 'n', 'date_of_birth', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'y', 'y', 'y', '', 'n', 'y', 'y'),
('0912', 'Place of Birth', 'mt_tree', 'L', '0912', '15', 'N', 'y', 'place_of_birth', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0913', 'Locality of Birth', 'mt_tree', 'L', '0913', '63', 'N', 'y', 'locality_of_birth', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0915', 'Sex', 'mt_select', 'L', '0915', '39', 'N', 'n', 'sex', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', 'y', 'y', '', 'n', 'y', 'n'),
('0916', 'Sexual Orientation', 'mt_select', 'L', '0916', '67', 'N', 'y', 'sexual_orientation', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0917', 'Identification Documents', 'textarea', 'M', '0917', '0', 'N', 'n', 'identification_documents', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0918', 'Civil Status', 'mt_select', 'L', '0918', '08', 'N', 'y', 'civil_status', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0919', 'Dependants', 'text', 'N', '0919', '0', 'N', 'y', 'dependants', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0920', 'Formal Education', 'mt_tree', 'L', '0920', '09', 'N', 'y', 'formal_education', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0921', 'Other Training', 'text', 'M', '0921', '0', 'N', 'n', 'other_training', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0922', 'Occupation', 'mt_tree', 'L', '0922', '10', 'Y', 'y', 'occupation', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0923', 'Local Term for Occupation', 'mt_tree', 'L', '0923', '64', 'Y', 'y', 'local_term_for_occupation', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0924', 'Health', 'text', 'M', '0924', '0', 'N', 'n', 'health', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0925', 'Medical records', 'textarea', 'M', '0925', '0', 'N', 'n', 'medical_records', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0926', 'Physical description', 'mt_select', 'L', '0926', '11', 'Y', 'y', 'physical_description', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0927', 'Deceased', 'checkbox', 'Y', '0927', '0', 'N', 'y', 'deceased', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0928', 'Date Deceased', 'date', 'D', '0928', '0', 'N', 'n', 'date_deceased', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0930', 'Group description', 'textarea', 'M', '0930', '0', 'N', 'n', 'group_description', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0931', 'Number of persons in group', 'text', 'N', '0931', '0', 'N', 'y', 'number_of_persons_in_group', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0940', 'Religion', 'mt_tree', 'L', '0940', '12', 'N', 'y', 'religion', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0941', 'Citizenship', 'mt_tree', 'L', '0941', '15', 'Y', 'y', 'citizenship', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0942', 'Ethnic Background', 'mt_select', 'L', '0942', '13', 'Y', 'y', 'ethnic_background', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0943', 'Other Background', 'mt_select', 'L', '0943', '65', 'Y', 'y', 'other_background', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0944', 'General Characteristics', 'mt_tree', 'L', '0944', '23', 'Y', 'n', 'general_characteristics', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0945', 'Language', 'mt_select', 'L', '0945', '14', 'Y', 'y', 'language', NULL, NULL, 'Y', '0', 'Y', '0', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0946', 'Local Language', 'mt_select', 'L', '0946', '66', 'Y', 'y', 'local_language', NULL, NULL, 'Y', '0', 'Y', '0', '0', NULL, 'Person', 'N', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0947', 'National Origin', 'mt_tree', 'L', '0947', '15', 'Y', 'n', 'national_origin', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0950', 'Remarks', 'textarea', 'M', '0950', '0', 'N', 'n', 'remarks', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0953', 'Reliability as Source', 'mt_select', 'L', '0953', '42', 'N', 'y', 'reliability_as_source', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0954', 'Reliability as Intervening Party', 'mt_select', 'L', '0954', '42', 'N', 'y', 'reliability_as_intervening_party', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0957', 'Files', 'textarea', 'C', '0957', '0', 'N', 'n', 'files', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0960', 'Date Received', 'date', 'D', '0960', '0', 'N', 'y', 'date_received', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0961', 'Date of Entry', 'date', 'D', '0961', '0', 'N', 'n', 'date_of_entry', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0962', 'Entered by', 'hidden', 'C', '0962', '0', 'N', 'n', 'entered_by', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0963', 'Project Title', 'text', 'M', '0963', '0', 'N', 'n', 'project_title', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0965', 'Comments', 'textarea', 'M', '0965', '0', 'N', 'n', 'comments', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'y', 'n'),
('0966', 'Supporting Documents', 'document', 'M', '0966', '0', 'N', 'n', 'supporting_documents', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'n', '', 'n', 'n', 'n'),
('0968', 'Record Grouping', 'text', 'C', '0968', '0', 'N', 'n', 'record_grouping', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'Person', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0970', 'Date Updated', 'date', 'D', '0970', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('0971', 'Updated By', 'hidden', 'M', '0971', '0', 'N', 'n', 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'Person', 'Y', 'n', 'y', 'n', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('113_1', 'Initial Date Type', 'mt_select', NULL, '113_1', '48', NULL, 'n', 'initial_date_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'event', NULL, 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('114_1', 'Final Date Type', 'mt_select', NULL, '114_1', '48', NULL, 'n', 'final_date_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'event', NULL, 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('2101', 'Act Record Number', 'hidden', 'I', '2101', '0', 'N', 'n', 'act_record_number', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2102', 'Victim', 'hidden', 'X', '2102', '0', 'N', 'n', 'victim', 'person', 'person_name', 'Y', '0', 'Y', '1', '0', NULL, 'act', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2103', 'Event', 'hidden', 'Z', '2103', '0', 'N', 'n', 'event', 'event', 'event_title', 'Y', '0', 'Y', '1', '0', NULL, 'act', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2108', 'Confidentiality', 'radio', 'Y', '2108', '0', 'N', 'n', 'confidentiality', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2109', 'Type of Act', 'mt_tree', 'L', '2109', '04', 'N', 'n', 'type_of_act', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'y', 'y', 'y'),
('2111', 'Initial Date', 'date', 'D', '2111', '0', 'N', 'n', 'initial_date', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2111_1', 'Initial Date Type', 'mt_select', 'L', '2111_1', '48', 'N', 'n', 'initial_date_type', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2112', 'Exact Location', 'textarea', 'M', '2112', '0', 'N', 'n', 'exact_location', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2113', 'Stated Reason', 'textarea', 'M', '2113', '0', 'N', 'n', 'stated_reason', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2114', 'Method of Violence', 'mt_tree', 'L', '2114', '05', 'Y', 'y', 'method_of_violence', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2115', 'Attribution', 'mt_select', 'L', '2115', '28', 'Y', 'y', 'attribution', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'act', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2116', 'Physical Consequences', 'textarea', 'M', '2116', '0', 'N', 'n', 'physical_consequences', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2117', 'Psychological Consequences', 'textarea', 'M', '2117', '0', 'N', 'n', 'psychological_consequences', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2118', 'Age at Time of Victimisation', 'text', 'T', '2118', '0', 'N', 'n', 'age_at_time_of_victimisation', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'act', 'N', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2121', 'Final Date', 'date', 'D', '2121', '0', 'N', 'n', 'final_date', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2121_1', 'Final Date Type', 'mt_select', 'L', '2121_1', '48', 'N', 'n', 'final_date_type', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2122', 'Exact Location at End of Act', 'textarea', 'M', '2122', '0', 'N', 'n', 'exact_location_at_end_of_act', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2123', 'Status at End of Act', 'mt_tree', 'L', '2123', '25', 'N', 'n', 'status_at_end_of_act', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2150', 'Remarks', 'textarea', 'M', '2150', '0', 'N', 'n', 'remarks', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2152', 'Victim Characteristics', 'mt_tree', 'L', '2152', '23', 'Y', 'y', 'victim_characteristics', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'act', 'N', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2153', 'Type of Location', 'mt_tree', 'L', '2153', '17', 'N', 'y', 'type_of_location', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2154', 'National Legislation', 'mt_select', 'L', '2154', '62', 'Y', 'y', 'national_legislation', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'act', 'N', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2155', 'International Instruments', 'mt_tree', 'L', '2155', '06', 'Y', 'y', 'international_instruments', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'act', 'N', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2160', 'Date Received', 'date', 'D', '2160', '0', 'N', 'y', 'date_received', NULL, NULL, 'Y', '1', 'Y', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2161', 'Date of Entry', 'date', 'D', '2161', '0', 'N', 'n', 'date_of_entry', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2162', 'Entered by', 'hidden', 'C', '2162', '0', 'N', 'n', 'entered_by', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2165', 'Comments', 'textarea', 'M', '2165', '0', 'N', 'n', 'comments', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2166', 'Supporting Documents', 'document', 'M', '2166', '0', 'N', 'n', 'supporting_documents', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'act', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'n', 'n'),
('2170', 'Date Updated', 'date', 'D', '2170', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'Y', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2171', 'Updated By', 'hidden', 'M', '2171', '0', 'N', 'n', 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'act', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2201', 'Chain of Events Record Number', 'hidden', 'I', '2201', '0', 'N', NULL, 'chain_of_events_record_number', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'y'),
('2202', 'Event', 'hidden', 'Z', '2202', '0', 'N', NULL, 'event', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'n', 'n'),
('2203', 'Related Event', 'related_event', 'Z', '2203', '0', 'N', NULL, 'related_event', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'N', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'y', 'n', 'n'),
('2209', 'Type of Chain of Events', 'mt_select', 'L', '2209', '22', 'N', NULL, 'type_of_chain_of_events', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'y', 'y', 'y'),
('2250', 'Remarks', 'textarea', 'M', '2250', '0', 'N', NULL, 'remarks', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'n'),
('2261', 'Date of Entry', 'date', 'D', '2261', '0', 'N', NULL, 'date_of_entry', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'n'),
('2262', 'Entered by', 'hidden', 'C', '2262', '0', 'N', NULL, 'entered_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'n', 'y', '', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2265', 'Comments', 'textarea', 'M', '2265', '0', 'N', NULL, 'comments', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'n'),
('2270', 'Date Updated', 'date', 'D', '2270', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'n'),
('2271', 'Updated by', 'hidden', 'M', '2271', '0', 'N', NULL, 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'chain_of_events', 'Y', 'n', 'y', '', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2301', 'Biographic Details Record Number', 'hidden', 'I', '2301', '0', 'N', NULL, 'biographic_details_record_number', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'y'),
('2302', 'Person', 'hidden', 'X', '2302', '0', 'N', NULL, 'person', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'N', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'n', 'n'),
('2303', 'Related Person', 'related_person', 'X', '2303', '0', 'N', NULL, 'related_person', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'N', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'n', 'n'),
('2308', 'Confidentiality', 'radio', 'Y', '2308', '0', 'N', NULL, 'confidentiality', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2309', 'Type of relationship', 'mt_select', 'L', '2309', '21', 'N', 'y', 'type_of_relationship', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'y'),
('2310', 'Initial Date', 'date', 'D', '2310', '0', 'N', 'y', 'initial_date', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2310_1', 'Initial Date Type', 'mt_select', NULL, '2310_1', '48', 'N', NULL, 'initial_date_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'biographic_details', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2311', 'Final Date', 'date', 'D', '2311', '0', 'N', 'y', 'final_date', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2311_1', 'Final Date Type', 'mt_select', NULL, '2311_1', '48', 'N', NULL, 'final_date_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'biographic_details', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2320', 'Education and Training', 'mt_select', 'L', '2320', '09', 'N', 'y', 'education_and_training', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2322', 'Employment', 'text', 'M', '2322', '0', 'N', NULL, 'employment', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2323', 'Affiliation', 'text', 'M', '2323', '0', 'N', NULL, 'affiliation', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2327', 'Position in Organisation', 'text', 'M', '2327', '0', 'N', NULL, 'position_in_organisation', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2328', 'Rank', 'text', 'M', '2328', '0', 'N', NULL, 'rank', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2350', 'Remarks', 'text', 'M', '2350', '0', 'N', NULL, 'remarks', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2361', 'Date of Entry', 'date', 'D', '2361', '0', 'N', NULL, 'date_of_entry', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'n'),
('2362', 'Entered by', 'hidden', 'C', '2362', '0', 'N', NULL, 'entered_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', '', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2365', 'Comments', 'textarea', 'M', '2365', '0', 'N', NULL, 'comments', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'n'),
('2370', 'Date Updated', 'date', 'D', '2370', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'n'),
('2371', 'Updated by', 'hidden', 'M', '2371', '0', 'N', NULL, 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'biographic_details', 'Y', 'n', 'y', '', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('2401', 'Involvement Record Number', 'hidden', 'I', '2401', '0', 'N', 'n', 'involvement_record_number', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2402', 'Perpetrator', 'hidden', 'X', '2402', '0', 'N', 'n', 'perpetrator', 'person', 'person_name', 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'N', 'n', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2403', 'Event', 'hidden', 'Z', '2403', '0', 'N', 'n', 'event', 'event', 'event_title', 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'N', 'n', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2404', 'Act', 'hidden', 'C', '2404', '0', 'N', 'n', 'act', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'n', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2408', 'Confidentiality', 'radio', 'Y', '2408', '0', 'N', 'n', 'confidentiality', NULL, NULL, 'N', '1', 'N', '0', '0', '0', 'Involvement', 'N', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2409', 'Degree of involvement', 'mt_tree', 'L', '2409', '18', 'N', 'y', 'degree_of_involvement', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'y', 'y', 'y'),
('2412', 'Type of Perpetrator', 'mt_tree', 'L', '2412', '24', 'Y', 'y', 'type_of_perpetrator', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2422', 'Latest Status as Perpetrator in the act', 'mt_tree', 'L', '2422', '26', 'N', 'y', 'latest_status_as_perpetrator_in_the_act', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2450', 'Remarks', 'textarea', 'M', '2450', '0', 'N', 'n', 'remarks', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'involvement', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2461', 'Date of Entry', 'date', 'D', '2461', '0', 'N', 'n', 'date_of_entry', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2462', 'Entered by', 'hidden', 'C', '2462', '0', 'N', 'n', 'entered_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2465', 'Comments', 'textarea', 'M', '2465', '0', 'N', 'n', 'comments', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'involvement', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2466', 'Supporting Documents', 'document', 'M', '2466', '0', 'N', 'n', 'supporting_documents', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'involvement', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', 'n', 'n', '', 'n', 'n', 'n'),
('2470', 'Date Updated', 'date', 'D', '2470', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2471', 'Updated by', 'hidden', 'M', '2471', '0', 'N', 'n', 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'involvement', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2501', 'Information record number', 'hidden', 'I', '2501', '0', 'N', 'n', 'information_record_number', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'information', 'Y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2502', 'Source', 'hidden', 'X', '2502', '0', 'N', 'n', 'source', 'person', 'person_name', 'Y', '0', 'N', '1', '0', NULL, 'information', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2503', 'Event', 'hidden', 'Z', '2503', '0', 'N', 'n', 'event', 'event', 'event_title', 'Y', '0', 'N', '1', '0', NULL, 'information', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2504', 'Related Person', 'related_person', 'X', '2504', '0', 'N', 'n', 'related_person', 'person', 'person_name', 'Y', '0', 'N', '1', '0', NULL, 'information', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2508', 'Confidentiality', 'radio', 'Y', '2508', '0', 'N', 'n', 'confidentiality', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2509', 'Source Connection to Information', 'mt_select', 'L', '2509', '19', 'N', 'y', 'source_connection_to_information', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'information', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'y', 'y', 'y'),
('2510', 'Language of Source Material', 'mt_select', 'L', '2510', '14', 'Y', 'y', 'language_of_source_material', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2511', 'Date of Source Material', 'date', 'D', '2511', '0', 'N', 'y', 'date_of_source_material', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2512', 'Type of Source Material', 'mt_select', 'L', '2512', '16', 'Y', 'y', 'type_of_source_material', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2513', 'Local Language of Source Material', 'mt_select', 'L', '2513', '66', 'Y', 'y', 'local_language_of_source_material', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'N', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2550', 'Remarks', 'textarea', 'M', '2550', '0', 'N', 'n', 'remarks', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2553', 'Reliability of Information', 'mt_select', 'L', '2553', '42', 'N', 'y', 'reliability_of_information', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'information', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2560', 'Date Received', 'date', 'D', '2560', '0', 'N', 'y', 'date_received', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2561', 'Date of Entry', 'date', 'D', '2561', '0', 'N', 'n', 'date_of_entry', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'information', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2562', 'Entered by', 'hidden', 'C', '2562', '0', 'N', 'n', 'entered_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'information', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2565', 'Comments', 'textarea', 'M', '2565', '0', 'N', 'n', 'comments', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2566', 'Supporting Documents', 'document', 'M', '2566', '0', 'N', 'n', 'supporting_documents', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'information', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', 'n', 'n', '', 'n', 'n', 'n'),
('2570', 'Date Updated', 'date', 'D', '2570', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'information', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2571', 'Updated by', 'hidden', 'M', '2571', '0', 'N', 'n', 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'information', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2601', 'Intervention Record Number', 'hidden', 'C', '2601', '0', 'N', 'n', 'intervention_record_number', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'n', '', 'n', 'y', 'y'),
('2602', 'Intervening Party', 'hidden', 'X', '2602', '0', 'N', 'n', 'intervening_party', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2603', 'Event', 'hidden', 'Z', '2603', '0', 'N', 'n', 'event', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2604', 'Victim', 'related_victim', 'X', '2604', '0', 'N', 'n', 'victim', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'N', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2608', 'Confidentiality', 'radio', 'Y', '2608', '0', 'N', 'n', 'confidentiality', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2609', 'Type of intervention', 'mt_tree', 'L', '2609', '20', 'Y', 'y', 'type_of_intervention', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', 'y', 'y', 'y'),
('2611', 'Date of intervention', 'date', 'D', '2611', '0', 'N', 'y', 'date_of_intervention', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2612', 'Parties Requested', 'textarea', 'M', '2612', '0', 'N', 'n', 'parties_requested', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2613', 'Response', 'mt_select', 'L', '2613', '27', 'N', 'y', 'response', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2614', 'Impact on the situation', 'mt_select', 'L', '2614', '44', 'N', 'y', 'impact_on_the_situation', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2650', 'Remarks', 'textarea', 'M', '2650', '0', 'N', 'n', 'remarks', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2651', 'Intervention status', 'mt_select', 'L', '2651', '45', 'N', 'y', 'intervention_status', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2652', 'Priority', 'mt_select', 'L', '2652', '46', 'N', 'n', 'priority', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', 'y', 'y'),
('2661', 'Date of Entry', 'date', 'D', '2661', '0', 'N', 'n', 'date_of_entry', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2662', 'Entered by', 'hidden', 'C', '2662', '0', 'N', 'n', 'entered_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2665', 'Comments', 'textarea', 'M', '2665', '0', 'N', 'n', 'comments', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', '', 'n', 'y', 'n'),
('2666', 'Supporting Documents', 'document', 'M', '2666', '0', 'N', 'n', 'supporting_documents', NULL, NULL, 'Y', '1', 'N', '0', '0', NULL, 'intervention', 'Y', 'n', 'y', 'y', '', 'y', 'n', 'n', 'n', 'y', '', 'n', 'n', 'n'),
('2670', 'Date Updated', 'date', 'D', '2670', '0', 'N', 'n', 'date_updated', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('2671', 'Updated by', 'hidden', 'M', '2671', '0', 'N', 'n', 'updated_by', NULL, NULL, 'Y', '0', 'N', '1', '0', NULL, 'intervention', 'Y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', '', 'n', 'y', 'n'),
('3102', 'Act Record Number', 'hidden', 'I', '3102', '0', 'N', NULL, 'arrest_record_number', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'n', 'n'),
('3110', 'Case Description', 'textarea', 'M', '3110', '0', 'N', NULL, 'case_description', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'y'),
('3112', 'Type of Detention', 'mt_select', 'L', '3112', '29', 'N', NULL, 'type_of_detention', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'y'),
('3113', 'Detention Conditions', 'textarea', 'M', '3113', '0', 'N', NULL, 'detention_conditions', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'n'),
('3114', 'Whereabouts and Outside Contact during Detention', 'mt_select', 'L', '3114', '30', 'Y', 'y', 'whereabouts', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'n'),
('3115', 'Legal Counsel', 'mt_select', 'L', '3115', '31', 'Y', 'y', 'legal_counsel', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'n'),
('3116', 'Type of Court', 'mt_select', 'L', '3116', '32', 'Y', 'y', 'type_of_court', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', '', NULL, 'y', 'n'),
('3117', 'Type of Language', 'mt_select', 'L', '3117', '33', 'N', 'y', 'type_of_language', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('3118', 'Court Case Code', 'text', 'M', '3118', '0', 'N', NULL, 'court_case_code', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('3119', 'Court Case Name', 'text', 'M', '3119', '0', 'N', NULL, 'court_case_name', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('3120', 'Judicial District', 'mt_select', 'L', '3120', '69', 'N', 'y', 'judicial_district', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'arrest', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', '', NULL, 'y', 'n'),
('3202', 'Act Record Number', 'hidden', 'I', '3202', '0', 'N', 'N', 'killing_record_number', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'killing', 'N', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', NULL, 'n', 'n', 'n'),
('3212', 'Autopsy', 'mt_select', 'L', '3212', '34', 'N', 'N', 'autopsy_results', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'killing', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', NULL, 'n', 'y', 'y'),
('3213', 'Death Certificate', 'mt_select', 'L', '3213', '35', 'N', 'N', 'death_certificate', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'killing', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', NULL, 'n', 'y', 'y'),
('3302', 'Act Record Number', 'hidden', 'I', '3302', '0', 'N', 'N', 'torture_record_number', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'torture', 'N', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', NULL, 'n', 'n', 'n'),
('3311', 'Statements Signed', 'mt_select', 'L', '3311', '36', 'Y', 'N', 'statements_signed', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'torture', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', NULL, 'n', 'y', 'y'),
('3312', 'Medical Attention', 'mt_select', 'L', '3312', '37', 'Y', 'Y', 'medical_attention', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'torture', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', NULL, 'n', 'y', 'y'),
('3351', 'Intent', 'mt_select', 'L', '3351', '38', 'Y', 'Y', 'intent', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'torture', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', NULL, 'n', 'y', 'y'),
('3402', 'Act Record Number', 'hidden', 'I', '3402', '0', 'N', 'N', 'destruction_record_number', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'destruction', 'N', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', NULL, 'n', 'n', 'n'),
('3410', 'Type of Property Loss', 'textarea', 'M', '3410', '0', 'N', 'N', 'type_of_property_loss', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'destruction', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', NULL, 'n', 'y', 'y'),
('3411', 'Value of Property Loss', 'text', 'C', '3411', '0', 'N', 'N', 'value_of_destroyed_property', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'destruction', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', NULL, 'n', 'y', 'y'),
('3412', 'Compensation', 'mt_select', 'L', '3412', '47', 'N', 'N', 'compensation', NULL, NULL, 'N', '0', 'N', '1', '0', NULL, 'destruction', 'N', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', NULL, 'n', 'y', 'y'),
('8001', 'Address Record Number', 'hidden', NULL, '8001', '0', 'N', 'n', 'address_record_number', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', '', 'n', 'y', 'y'),
('8002', 'Address Type', 'mt_select', NULL, '8002', '40', 'N', 'n', 'address_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', 'y', 'y'),
('8003', 'Address', 'textarea', NULL, '8003', '0', 'N', 'n', 'address', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', '', 'y', 'y', 'n'),
('8004', 'Country', 'mt_select', NULL, '8004', '15', 'N', 'n', 'country', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', 'y', 'n'),
('8005', 'Phone', 'text', NULL, '8005', '0', 'N', 'n', 'phone', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('8006', 'Cellular', 'text', NULL, '8006', '0', 'N', 'n', 'cellular', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('8007', 'Fax', 'text', NULL, '8007', '0', 'N', 'n', 'fax', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('8008', 'Email', 'text', NULL, '8008', '0', 'N', 'n', 'email', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('8009', 'Web', 'text', NULL, '8009', '0', 'N', 'n', 'web', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('8010', 'Start Date', 'date', NULL, '8010', '0', 'N', 'n', 'start_date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', 'y', 'n'),
('8011', 'End Date', 'date', NULL, '8011', '0', 'N', 'n', 'end_date', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'address', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', 'y', 'n'),
('9001', 'Document ID', 'hidden', NULL, '9001', '0', 'N', 'n', 'doc_id', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', 'y', 'y'),
('9002', 'Document Title', 'text', NULL, '9002', '0', 'N', 'n', 'title', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', 'y', 'y'),
('9003', 'Creator', 'text', NULL, '9003', '0', 'N', 'n', 'creator', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', '', 'n', 'y', 'n'),
('9004', 'Description', 'textarea', NULL, '9004', '0', 'n', 'n', 'description', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'n', 'y', '', 'n', '', 'n', 'y', 'n'),
('9005', 'Date Created', 'date', NULL, '9005', '0', 'N', 'n', 'datecreated', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'y', '', 'n', 'y', 'y'),
('9006', 'Date Submitted', 'date', NULL, '9006', '0', 'n', 'n', 'datesubmitted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('9007', 'Type', 'mt_select', NULL, '9007', '16', 'n', 'n', 'type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('9008', 'Language', 'text', NULL, '9008', '0', 'n', 'n', 'language', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', '', 'y', '', 'n', 'y', 'n'),
('9009', 'Choose File Upload', 'upload', NULL, '9009', '0', 'n', 'n', 'choose_file_upload', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'N', 'N', 'n', 'n', '', 'n', 'n', 'n'),
('9010', 'Format', 'hidden', NULL, '9010', '0', 'n', 'n', 'format', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'supporting_docs_meta', NULL, 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', '', 'n', 'y', 'n'),
('911_1', 'Date of Birth Type', 'mt_select', NULL, '911_1', '48', 'N', 'n', 'date_of_birth_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'person', NULL, 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n'),
('928_1', 'Date Deceased Type', 'mt_select', NULL, '928_1', '48', 'N', 'n', 'date_deceased_type', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'person', NULL, 'n', 'y', 'y', '', 'y', 'n', 'n', '', 'y', '', 'n', 'y', 'n');



UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE `field_name` LIKE '%record_number%' ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE `field_type` = 'mt_tree' OR `field_type` = 'textarea' ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE is_repeat='Y' || is_repeat='y';
UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE `data_dict`.`field_number` = '0166' LIMIT 1 ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE `data_dict`.`field_number` = '0966' LIMIT 1 ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE `data_dict`.`field_number` = '2166' LIMIT 1 ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE `data_dict`.`field_number` = '2466' LIMIT 1 ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' WHERE `data_dict`.`field_number` = '2566' LIMIT 1 ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' , visible_browse = 'n' , `visible_search` = 'N' , `visible_search_display` = 'N'  WHERE `data_dict`.`field_number` = '9009' LIMIT 1 ;
UPDATE `data_dict` SET `visible_browse_editable` = 'n' , visible_browse = 'n'   WHERE `data_dict`.`field_number` = '0910' LIMIT 1 ;



insert into data_dict_original (  `field_number` , `field_label` , `field_type` ,  `datatype` , `label_number` ,  `list_code` ,
`is_repeat` ,  `clar_note` ,   `field_name` , `link_table` , `link_field` , `remove` ,   `chk_remove` ,   `num_levels` ,   `lite` ,   `bool_def` ,   `numb_def`,    `entity`,    `find`,    `essential` ,   `enabled`, `visible_new`,`visible_edit`,`visible_view`, `visible_search` , `visible_search_display`, `visible_browse`, `validation` ,  `required`, `visible_adv_search`, `visible_adv_search_display`) 
Select   `field_number` , `field_label` , `field_type` ,  `datatype` , `label_number` ,  `list_code` ,
`is_repeat` ,  `clar_note` ,   `field_name` , `link_table` , `link_field` ,  `remove` ,   `chk_remove` ,   `num_levels` ,   `lite` ,   `bool_def` ,   `numb_def`,    `entity`,    `find`,    `essential` ,   `enabled`, `visible_new`,`visible_edit`,`visible_view`, `visible_search` , `visible_search_display`,  `visible_browse`, `validation` ,  `required`, `visible_adv_search`, `visible_adv_search_display` FROM data_dict;

