<?php

$change_password_form = array(
    
    'password_current'=>array('type'=>'password','label'=>_t('CURRENT_PASSWORD')),

    'password1'=>array('type'=>'password','label'=>_t('NEW_PASSWORD')),
    'password2'=>array('type'=>'password','label'=>_t('CONFIRM_NEW_PASSWORD')),

    
    
    'save' => array('type'=>'submit','label'=>_t('SAVE')),
    'cancel' => array('type'=>'submit','label'=>_t('CANCEL'))                     
);
